language: python

python:
  - 3.7

dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - black . --check -l 80
    #- find ./ -name "*.py" | isort --check-only -m 3
    #- pytest
